# serverless.yml

service: express-api

custom: ${file(serverless.env.yml)}

provider:
  name: aws
  stage: dev
  region: us-east-2
  environment:
    DB_URI: ${self:custom.${opt:stage}.mongodb_uri}
    HTTP_USER: ${self:custom.auth.username}
    HTTP_PASS: ${self:custom.auth.password}

functions:

  # DB access for webapp
  getDeaths:
    runtime: nodejs8.10
    handler: app.handler
    events:
      - http: GET /deaths

  # Upload route for crawler
  postDeath:
    runtime: nodejs8.10
    handler: app.handler
    events:
      - http: 'POST /deaths'

  # Grab headlines from Reddit
  reddit:
    runtime: python3.6
    handler: crawler/handler.run
    events:
      - schedule: rate(2 hours)
    environment:
      API: ${self:custom.${opt:stage}.api_host}
      PHONEBOOK: ${self:custom.${opt:stage}.phonebook}
      GRAVEYARD: ${self:custom.${opt:stage}.graveyard}


plugins:
  - serverless-python-requirements
  - serverless-offline
